config = {
    'all_classes': [
        'shirt, blouse',
        'top, t-shirt, sweatshirt',
        'sweater',
        'cardigan',
        'jacket',
        'vest',
        'pants',
        'shorts',
        'skirt',
        'coat',
        'dress',
        'jumpsuit',
        'hat',
        'tie',
        'shoe',
        'bag, wallet'
    ],
    'labels': {
        0: 'shirt, blouse',
        1: 'top, t-shirt, sweatshirt',
        2: 'sweater',
        3: 'cardigan',
        4: 'jacket',
        5: 'vest',
        6: 'pants',
        7: 'shorts',
        8: 'skirt',
        9: 'coat',
        10: 'dress',
        11: 'jumpsuit',
        12: 'cape',
        13: 'glasses',
        14: 'hat',
        15: 'headband, head covering, hair accessory',
        16: 'tie',
        17: 'glove',
        18: 'watch',
        19: 'belt',
        20: 'leg warmer',
        21: 'tights, stockings',
        22: 'sock',
        23: 'shoe',
        24: 'bag, wallet',
        25: 'scarf',
        26: 'umbrella',
        27: 'hood',
        28: 'collar',
        29: 'lapel',
        30: 'epaulette',
        31: 'sleeve',
        32: 'pocket',
        33: 'neckline',
        34: 'buckle',
        35: 'zipper',
        36: 'applique',
        37: 'bead',
        38: 'bow',
        39: 'flower',
        40: 'fringe',
        41: 'ribbon',
        42: 'rivet',
        43: 'ruffle',
        44: 'sequin',
        45: 'tassel'
    },
    'models': 'models/maskrcnn_checkpoint_8_epoch.pth',
    'DEVICE': 'cpu'
}
